{
   "layout":{
      "name":"root",
      "widget":"KXLinearLayout",
      "ios_auto_edge":true,
      "attr":[
         {
            "name":"size",
            "value":{
               "width":"match_parent",
               "height":"match_parent"
            }
         },
         {
            "name":"orientation",
            "value":"vertical"
         },
         {
            "name":"color",
            "value":"#ffffff"
         }
      ],
      "subviews":[
         {
            "name":"",
            "widget":"KXLinearLayout",
            "attr":[
               {
                  "name":"size",
                  "value":{
                     "width":"match_parent",
                     "height":"60dp"
                  }
               },
               {
                  "name":"orientation",
                  "value":"horizontal"
               },
               {
                  "name":"color",
                  "value":"clear"
               },
               {
                  "name":"weight",
                  "value":0
               }
            ],
            "subviews":[
               {
                  "name":"label1",
                  "widget":"UILabel",
                  "attr":[
                     {
                        "name":"size",
                        "value":{
                           "width":"auto",
                           "height":"match_parent"
                        }
                     },
                     {
                        "name":"color",
                        "value":"clear"
                     },
                     {
                        "name":"weight",
                        "value":1
                     },
                     {
                        "name":"text",
                        "value":"Coffee or tea?"
                     },
                     {
                        "name":"text_color",
                        "value":"#202020"
                     },
                     {
                        "name":"margins",
                        "value":{
                           "left":"4dp",
                           "top":"0dp",
                           "right":"4dp",
                           "bottom":"0dp"
                        }
                     },
                     {
                        "name":"gravity",
                        "value":"center"
                     }
                  ]
               },
               {
                  "name":"switch1",
                  "widget":"UISwitch",
                  "attr":[
                     {
                        "name":"size",
                        "value":{
                           "width":"94dp",
                           "height":"match_parent"
                        }
                     },
                     {
                        "name":"color",
                        "value":"clear"
                     },
                     {
                        "name":"weight",
                        "value":0
                     },
                     {
                        "name":"on",
                        "value": true
                     },                     
                     {
                        "name":"margins",
                        "value":{
                           "left":"4dp",
                           "top":"0dp",
                           "right":"4dp",
                           "bottom":"0dp"
                        }
                     },
                     {
                        "name":"gravity",
                        "value":"center"
                     }
                  ]
               }
            ]
         }
      ]
   }
}